name: run spyder

on:
  push:               # 每次 push 時執行
    branches:
      - main          # 指定 main branch
  schedule:           # 每天早上9點執行
    - cron: '0 1 * * *'
  workflow_dispatch:  # 手動觸發

permissions:
  contents: write 

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 安裝套件
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 執行 code
      - name: Run api.py
        run: python api.py

      - name: Run static.py
        run: python static.py

      # 把寫好的CSV commit
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Add generated CSV"
          git push