name: run spyder

on:
  push:               # 每次 push 時執行
    branches:
      - main          # 指定 main branch（可以改成你自己的）
  schedule:           # 每 30 分鐘執行一次
    - cron: '*/5 * * * *'
  workflow_dispatch:  # 手動觸發

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run api.py
        run: python api.py

      - name: Run static.py
        run: python static.py