name: Run Python Scripts Daily

on:
  schedule:
    - cron: '0 1 * * *'  # UTC 時間，等於台灣時間早上 9 點
  workflow_dispatch:     # 可以手動觸發

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run api.py
        run: python api.py

      - name: Run static.py
        run: python static.py
